// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("assetTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("purchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("serialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("statusId")
                        .HasColumnType("text");

                    b.Property<DateTime>("warrantyEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("assetTypeId");

                    b.HasIndex("statusId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("backend.Entities.AssetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("assetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("returnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("assetId");

                    b.HasIndex("userId");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("backend.Entities.AssetStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AssetStatuses");
                });

            modelBuilder.Entity("backend.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("backend.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("backend.Entities.ImpactLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ImpactLevels");
                });

            modelBuilder.Entity("backend.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("backend.Entities.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("firstResponseTime")
                        .HasColumnType("interval");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("priorityId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("resolutionTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("priorityId");

                    b.ToTable("SlaPolicy");
                });

            modelBuilder.Entity("backend.Entities.SlaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlaPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("firstResponseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("firstResponseDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("pauseReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("pausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("policyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("resolutionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("resolutionDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("resumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ticketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SlaPolicyId");

                    b.HasIndex("ticketId");

                    b.ToTable("SlaRecord");
                });

            modelBuilder.Entity("backend.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("backend.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleInTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("backend.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("assignedToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("categoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("closedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("createdById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("firstResponseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("impactLevelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("priorityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("resolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("slaDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("statusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("subcategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("teamId")
                        .HasColumnType("uuid");

                    b.Property<string>("ticketDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ticketNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ticketTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("urgencyLevelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("assignedToId");

                    b.HasIndex("categoryId");

                    b.HasIndex("createdById");

                    b.HasIndex("impactLevelId");

                    b.HasIndex("priorityId");

                    b.HasIndex("statusId");

                    b.HasIndex("subcategoryId");

                    b.HasIndex("teamId");

                    b.HasIndex("urgencyLevelId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("backend.Entities.TicketAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("assignedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("assignedToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ticketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("assignedById");

                    b.HasIndex("assignedToId");

                    b.HasIndex("ticketId");

                    b.ToTable("TicketAssignments");
                });

            modelBuilder.Entity("backend.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TicketCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketCommentId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UploadedById");

                    b.ToTable("TicketAttachments");
                });

            modelBuilder.Entity("backend.Entities.TicketCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("parentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TicketCategories");
                });

            modelBuilder.Entity("backend.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("backend.Entities.TicketPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("resolutionTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("responseTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("TicketPriorities");
                });

            modelBuilder.Entity("backend.Entities.TicketStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TicketStatuses");
                });

            modelBuilder.Entity("backend.Entities.TicketStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChangerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OldStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketStatusHistories");
                });

            modelBuilder.Entity("backend.Entities.TicketSubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("categoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("TicketSubCategories");
                });

            modelBuilder.Entity("backend.Entities.UrgencyLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UrgencyLevels");
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("backend.Entities.Asset", b =>
                {
                    b.HasOne("backend.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("assetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.AssetStatus", "status")
                        .WithMany()
                        .HasForeignKey("statusId");

                    b.Navigation("AssetType");

                    b.Navigation("status");
                });

            modelBuilder.Entity("backend.Entities.AssetAssignment", b =>
                {
                    b.HasOne("backend.Entities.Asset", "Asset")
                        .WithMany("Assignments")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Department", b =>
                {
                    b.HasOne("backend.Entities.Department", "ParentDepartment")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDepartmentId");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("backend.Entities.SlaPolicy", b =>
                {
                    b.HasOne("backend.Entities.TicketPriority", "Priority")
                        .WithMany("SlaPolicies")
                        .HasForeignKey("priorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("backend.Entities.SlaRecord", b =>
                {
                    b.HasOne("backend.Entities.SlaPolicy", "SlaPolicy")
                        .WithMany("SlaRecords")
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Ticket", "Ticket")
                        .WithMany("SlaRecords")
                        .HasForeignKey("ticketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlaPolicy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("backend.Entities.Team", b =>
                {
                    b.HasOne("backend.Entities.Department", "Department")
                        .WithMany("Teams")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("backend.Entities.TeamMember", b =>
                {
                    b.HasOne("backend.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Ticket", b =>
                {
                    b.HasOne("backend.Entities.User", null)
                        .WithMany("AssignedTickets")
                        .HasForeignKey("UserId");

                    b.HasOne("backend.Entities.User", null)
                        .WithMany("CreatedTickets")
                        .HasForeignKey("UserId1");

                    b.HasOne("backend.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("assignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Entities.TicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("createdById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Entities.ImpactLevel", "ImpactLevel")
                        .WithMany()
                        .HasForeignKey("impactLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.TicketPriority", "Priority")
                        .WithMany("Tickets")
                        .HasForeignKey("priorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.TicketStatus", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("statusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.TicketSubCategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("subcategoryId");

                    b.HasOne("backend.Entities.Team", "TeamId")
                        .WithMany("Tickets")
                        .HasForeignKey("teamId");

                    b.HasOne("backend.Entities.UrgencyLevel", "UrgencyLevel")
                        .WithMany()
                        .HasForeignKey("urgencyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("ImpactLevel");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("Subcategory");

                    b.Navigation("TeamId");

                    b.Navigation("UrgencyLevel");
                });

            modelBuilder.Entity("backend.Entities.TicketAssignment", b =>
                {
                    b.HasOne("backend.Entities.TeamMember", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("assignedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.TeamMember", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("assignedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Ticket", "Ticket")
                        .WithMany("Assignments")
                        .HasForeignKey("ticketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("backend.Entities.TicketAttachment", b =>
                {
                    b.HasOne("backend.Entities.TicketComment", "TicketComment")
                        .WithMany()
                        .HasForeignKey("TicketCommentId");

                    b.HasOne("backend.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("TicketComment");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("backend.Entities.TicketComment", b =>
                {
                    b.HasOne("backend.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.TicketStatusHistory", b =>
                {
                    b.HasOne("backend.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.TicketStatus", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.TicketStatus", "OldStatus")
                        .WithMany()
                        .HasForeignKey("OldStatusId");

                    b.HasOne("backend.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("backend.Entities.TicketSubCategory", b =>
                {
                    b.HasOne("backend.Entities.TicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.HasOne("backend.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("backend.Entities.UserRole", b =>
                {
                    b.HasOne("backend.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.Asset", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("backend.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("backend.Entities.Department", b =>
                {
                    b.Navigation("SubDepartments");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("backend.Entities.SlaPolicy", b =>
                {
                    b.Navigation("SlaRecords");
                });

            modelBuilder.Entity("backend.Entities.Team", b =>
                {
                    b.Navigation("TeamMembers");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("backend.Entities.Ticket", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("SlaRecords");
                });

            modelBuilder.Entity("backend.Entities.TicketPriority", b =>
                {
                    b.Navigation("SlaPolicies");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("backend.Entities.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("TeamMembers");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
